name: CI-test

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Tset
        run: |
          touch ./test-file
          cat >> ./test-file <<EOF
          line 1
          line 2
          line 3
          # line 4
          EOF

      - name : Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: test-file
          path: test-file
